#!/bin/bash

# First command with its own 60-second duration
end=$((SECONDS+60))
while [ $SECONDS -lt $end ]; do
    sudo sntp 169.254.169.123 > sntp_amazon_result.txt 2>&1
    sleep 1
done

# Reset the timer for the second command
end=$((SECONDS+60))
while [ $SECONDS -lt $end ]; do
    sudo sntp time.apple.com > sntp_apple_result.txt 2>&1
    sleep 1
done
